"""Per-type index pages rendered by ``repo-ledger index`` (written red-first)."""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

import pytest

from repo_ledger.cli import main
from repo_ledger.config import LedgerConfig
from repo_ledger.errors import LedgerError

CANONICAL_HEADER = (
    "| id | name | status | parent | order | anchor | supersedes | date | legacy | note |\n"
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
OWNER_HEADER = (
    "| id | name | status | parent | order | owner | legacy | supersedes | date | note |\n"
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
TYPES = """
[types.TASK]
allowed_statuses = ["BACKLOG", "READY", "IN_PROGRESS", "BLOCKED", "DONE", "DROPPED"]
description = "Work items"

[types.ISSUE]
allowed_statuses = ["OPEN", "INVESTIGATING", "RESOLVED", "WONT_FIX"]

[types.MODEL]
allowed_statuses = ["DRAFT", "IN_FORCE", "SUPERSEDED"]
"""
DOT = " · "
LINK = "[`docs/proposal.md`](../proposal.md)"
DEFAULT_STATUS = {"TASK": "READY", "ISSUE": "OPEN", "MODEL": "DRAFT"}


def cell(value):
    return value.replace("\\", "\\\\").replace("|", "\\|")


def row(entity_id, name, *, status=None, parent="", order=None, anchor="docs/proposal.md",
        supersedes="", date="2026-09-01", legacy="", note="", layout="canonical"):
    type_name, serial = entity_id.rsplit("-", 1)
    status = status or DEFAULT_STATUS[type_name]
    order = serial if order is None else str(order)
    if layout == "owner":
        cells = [entity_id, name, status, parent, order, anchor, legacy, supersedes, date, note]
    else:
        cells = [entity_id, name, status, parent, order, anchor, supersedes, date, legacy, note]
    return "| " + " | ".join(cell(value) for value in cells) + " |\n"


def make_project(root, rows, *, index="", independent_order=False, layout="canonical", git=False):
    root.mkdir(parents=True, exist_ok=True)
    if git:
        subprocess.run(["git", "init", str(root)], check=True, capture_output=True)
    config = ('[ledger]\nschema_version = "1.0"\nregistry_path = ".ledger/ENTITY_REGISTRY.md"\n'
              f"independent_order = {'true' if independent_order else 'false'}\n" + TYPES)
    if index:
        config += "\n[index]\n" + index
    (root / "ledger.toml").write_text(config, encoding="utf-8")
    (root / "docs").mkdir(exist_ok=True)
    (root / "docs" / "proposal.md").write_text("# Proposal\n", encoding="utf-8")
    registry = root / ".ledger" / "ENTITY_REGISTRY.md"
    registry.parent.mkdir(exist_ok=True)
    header = OWNER_HEADER if layout == "owner" else CANONICAL_HEADER
    registry.write_text("<!-- schema: 1.0 -->\n# Entity Registry\n\n" + header + "".join(rows),
                        encoding="utf-8")
    if git:
        subprocess.run(["git", "-C", str(root), "add", "."], check=True, capture_output=True)
    return root


def index(capsys, root, *extra):
    capsys.readouterr()
    code = main(["index", "--root", str(root), "--json", *extra])
    return code, json.loads(capsys.readouterr().out)


def generate(capsys, root, out="docs/index"):
    code, report = index(capsys, root, "--out", str(root / out))
    assert code == 0, report
    return root / out


def text(path):
    return path.read_text(encoding="utf-8")


def entity_headings(page):
    return [line for line in page.splitlines() if line.startswith("##")]


def fields_of(page, entity_id):
    """Return the compact field line of an entity rendered as a heading or a bullet."""
    lines = page.splitlines()
    for number, line in enumerate(lines):
        if line.startswith("##") and line.split(" ", 2)[1] == entity_id:
            assert lines[number + 1] == ""
            return lines[number + 2]
        if line.lstrip(" ").startswith(f"- {entity_id} "):
            return line.lstrip(" ").split(DOT, 1)[1]
    raise AssertionError(f"{entity_id} is not rendered")


def snapshot(directory):
    if not directory.exists():
        return None
    return {path.name: path.read_bytes() for path in sorted(directory.iterdir())}


def fingerprint(root):
    return hashlib.sha256((root / ".ledger" / "ENTITY_REGISTRY.md").read_bytes()).hexdigest()[:12]


def header(root):
    return (f"<!-- registry: .ledger/ENTITY_REGISTRY.md; registry-sha256: {fingerprint(root)}; "
            "generated by repo-ledger index; do not edit by hand -->")


def test_flat_type_renders_every_entity_as_a_level_two_heading(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha"), row("TASK-2", "Beta"),
                                         row("TASK-3", "Gamma")])
    page = text(generate(capsys, root) / "TASK.md")

    assert entity_headings(page) == ["## TASK-1 Alpha", "## TASK-2 Beta", "## TASK-3 Gamma"]
    assert fields_of(page, "TASK-2") == DOT.join(["status: READY", "date: 2026-09-01", f"anchor: {LINK}"])


def test_three_level_tree_nests_by_heading_level(tmp_path, capsys):
    rows = [row("TASK-1", "Root"), row("TASK-2", "Child", parent="TASK-1"),
            row("TASK-3", "Grandchild", parent="TASK-2"), row("TASK-4", "Second root"),
            row("TASK-5", "Second child", parent="TASK-1")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")

    assert entity_headings(page) == [
        "## TASK-1 Root", "### TASK-2 Child", "#### TASK-3 Grandchild",
        "### TASK-5 Second child", "## TASK-4 Second root"]
    assert "parent:" not in fields_of(page, "TASK-3")


def test_entities_deeper_than_level_six_continue_as_nested_bullets(tmp_path, capsys):
    rows = [row("TASK-1", "Level 1")]
    rows += [row(f"TASK-{n}", f"Level {n}", parent=f"TASK-{n - 1}") for n in range(2, 9)]
    rows += [row("TASK-9", "Deep sibling", parent="TASK-5"),
             row("TASK-10", "Deeper sibling", parent="TASK-6")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")
    lines = page.splitlines()

    assert entity_headings(page) == ["## TASK-1 Level 1", "### TASK-2 Level 2", "#### TASK-3 Level 3",
                                     "##### TASK-4 Level 4", "###### TASK-5 Level 5"]
    bullets = [line for line in lines if line.lstrip(" ").startswith("- ")]
    assert [line.split(DOT)[0] for line in bullets] == [
        "- TASK-6 Level 6", "  - TASK-7 Level 7", "    - TASK-8 Level 8",
        "  - TASK-10 Deeper sibling", "- TASK-9 Deep sibling"]
    assert bullets[0] == DOT.join(["- TASK-6 Level 6", "status: READY", "date: 2026-09-01", f"anchor: {LINK}"])
    # One tight list that follows the level-6 heading block.
    start = lines.index(bullets[0])
    assert start > lines.index("###### TASK-5 Level 5")
    assert lines[start:start + len(bullets)] == bullets
    assert lines[start - 1] == ""


def test_cross_type_parent_is_shown_on_both_pages(tmp_path, capsys):
    rows = [row("TASK-1", "Parent task"), row("TASK-2", "Other task"),
            row("ISSUE-1", "Child issue", parent="TASK-1"), row("ISSUE-2", "Plain issue"),
            row("ISSUE-3", "Nested issue", parent="ISSUE-1")]
    out = generate(capsys, make_project(tmp_path / "p", rows))
    issues, tasks = text(out / "ISSUE.md"), text(out / "TASK.md")

    assert entity_headings(issues) == ["## ISSUE-1 Child issue", "### ISSUE-3 Nested issue",
                                       "## ISSUE-2 Plain issue"]
    assert fields_of(issues, "ISSUE-1").endswith(DOT + "parent: TASK-1 Parent task")
    assert "parent:" not in fields_of(issues, "ISSUE-3")

    assert entity_headings(tasks) == ["## TASK-1 Parent task", "## TASK-2 Other task"]
    lines = tasks.splitlines()
    children = lines.index("children of other types: ISSUE-1 Child issue")
    assert lines.index("## TASK-1 Parent task") < children < lines.index("## TASK-2 Other task")


def test_supersedes_is_rendered_in_both_directions(tmp_path, capsys):
    rows = [row("TASK-1", "Old plan"), row("TASK-2", "Middle plan"),
            row("TASK-3", "New plan", supersedes="TASK-1, TASK-2"),
            row("ISSUE-1", "Replacement issue", supersedes="TASK-2")]
    out = generate(capsys, make_project(tmp_path / "p", rows))
    tasks = text(out / "TASK.md")

    assert fields_of(tasks, "TASK-3").endswith("supersedes: TASK-1 Old plan; TASK-2 Middle plan")
    assert fields_of(tasks, "TASK-1").endswith("superseded by: TASK-3 New plan")
    assert fields_of(tasks, "TASK-2").endswith(
        "superseded by: TASK-3 New plan; ISSUE-1 Replacement issue")
    assert fields_of(text(out / "ISSUE.md"), "ISSUE-1").endswith("supersedes: TASK-2 Middle plan")


def test_plan_order_sorts_siblings_before_numeric_id(tmp_path, capsys):
    rows = [row("TASK-1", "Planned third", order=3), row("TASK-2", "Planned first", order=1),
            row("TASK-3", "Tied first", order=1),
            row("TASK-4", "Child planned second", parent="TASK-2", order=2),
            row("TASK-5", "Child planned first", parent="TASK-2", order=1)]
    root = make_project(tmp_path / "p", rows, independent_order=True)
    page = text(generate(capsys, root) / "TASK.md")

    assert entity_headings(page) == [
        "## TASK-2 Planned first", "### TASK-5 Child planned first", "### TASK-4 Child planned second",
        "## TASK-3 Tied first", "## TASK-1 Planned third"]


def test_without_independent_order_siblings_sort_by_numeric_id(tmp_path, capsys):
    rows = [row("TASK-1", "One"), row("TASK-2", "Two"), row("TASK-10", "Ten"),
            row("TASK-11", "Eleven", parent="TASK-2"), row("TASK-12", "Twelve", parent="TASK-2")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")

    assert entity_headings(page) == ["## TASK-1 One", "## TASK-2 Two", "### TASK-11 Eleven",
                                     "### TASK-12 Twelve", "## TASK-10 Ten"]


def test_owner_path_links_relative_to_the_page_and_commit_hash_stays_plain(tmp_path, capsys):
    rows = [row("TASK-1", "Path owner", layout="owner"),
            row("TASK-2", "Short hash owner", anchor="6042577", layout="owner"),
            row("TASK-3", "Full hash owner", anchor="a" * 40, layout="owner")]
    root = make_project(tmp_path / "p", rows, layout="owner")
    page = text(generate(capsys, root) / "TASK.md")

    assert DOT + "owner: [`docs/proposal.md`](../proposal.md)" in fields_of(page, "TASK-1")
    assert fields_of(page, "TASK-2").endswith(DOT + "owner: `6042577`")
    assert fields_of(page, "TASK-3").endswith(DOT + "owner: `" + "a" * 40 + "`")
    assert "](" not in fields_of(page, "TASK-2") + fields_of(page, "TASK-3")

    deeper = text(generate(capsys, root, out="catalogue/types") / "TASK.md")
    assert DOT + "owner: [`docs/proposal.md`](../../docs/proposal.md)" in fields_of(deeper, "TASK-1")


def test_unicode_names_are_written_verbatim_as_utf8(tmp_path, capsys):
    name = "中文任务 ✓ café 🚀"
    rows = [row("TASK-1", name, note="依赖 TASK-2 Ünïcode – ok"), row("TASK-2", "Ünïcode – ok")]
    out = generate(capsys, make_project(tmp_path / "p", rows))
    data = (out / "TASK.md").read_bytes()

    assert ("## TASK-1 " + name + "\n").encode("utf-8") in data
    assert fields_of(data.decode("utf-8"), "TASK-1").endswith("note: 依赖 TASK-2 Ünïcode – ok")


def test_type_without_entities_gets_a_page_that_says_so(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only task")])
    page = text(generate(capsys, root) / "MODEL.md")

    assert "No MODEL entity is registered. Back to the [overview](README.md)." in page.splitlines()
    assert entity_headings(page) == []
    for status in ("DRAFT", "IN_FORCE", "SUPERSEDED"):
        assert f"| {status} | 0 |" in page.splitlines()


def test_overview_lists_every_declared_type_with_counts_and_links(tmp_path, capsys):
    rows = [row("TASK-1", "A", status="DONE"), row("TASK-2", "B"), row("TASK-3", "C"),
            row("ISSUE-1", "D", status="RESOLVED")]
    root = make_project(tmp_path / "p", rows)
    out = generate(capsys, root)
    lines = text(out / "README.md").splitlines()

    assert lines[0] == header(root)
    assert f"Registry `.ledger/ENTITY_REGISTRY.md` (sha256 `{fingerprint(root)}`): 4 entities in 3 types." in lines
    table = [line for line in lines if line.startswith("| ")]
    assert table == [
        "| type | description | entities | by status | page |",
        "| --- | --- | --- | --- | --- |",
        "| TASK | Work items | 3 | READY 2, DONE 1 | [TASK.md](TASK.md) |",
        "| ISSUE |  | 1 | RESOLVED 1 | [ISSUE.md](ISSUE.md) |",
        "| MODEL |  | 0 | none | [MODEL.md](MODEL.md) |",
    ]
    for name in ("TASK.md", "ISSUE.md", "MODEL.md"):
        assert text(out / name).splitlines()[0] == header(root)


def test_pages_match_the_documented_format(tmp_path, capsys):
    rows = [row("TASK-1", "Root plan", status="DONE", legacy="OLD-1", note="kick-off"),
            row("TASK-2", "Child step", parent="TASK-1"),
            row("TASK-3", "Replacement step", parent="TASK-1", supersedes="TASK-2", note="replaces TASK-2"),
            row("ISSUE-1", "Found bug", parent="TASK-3")]
    root = make_project(tmp_path / "p", rows)
    out = generate(capsys, root)
    sha = fingerprint(root)

    assert text(out / "README.md") == "\n".join([
        header(root),
        "# Entity index",
        "",
        f"Registry `.ledger/ENTITY_REGISTRY.md` (sha256 `{sha}`): 4 entities in 3 types.",
        "",
        "| type | description | entities | by status | page |",
        "| --- | --- | --- | --- | --- |",
        "| TASK | Work items | 3 | READY 2, DONE 1 | [TASK.md](TASK.md) |",
        "| ISSUE |  | 1 | OPEN 1 | [ISSUE.md](ISSUE.md) |",
        "| MODEL |  | 0 | none | [MODEL.md](MODEL.md) |",
        ""])
    assert text(out / "TASK.md") == "\n".join([
        header(root),
        "# TASK entities",
        "",
        "Description: Work items",
        "",
        "3 entities. Back to the [overview](README.md).",
        "",
        "| status | entities |",
        "| --- | --- |",
        "| BACKLOG | 0 |",
        "| READY | 2 |",
        "| IN_PROGRESS | 0 |",
        "| BLOCKED | 0 |",
        "| DONE | 1 |",
        "| DROPPED | 0 |",
        "",
        "## TASK-1 Root plan",
        "",
        DOT.join(["status: DONE", "date: 2026-09-01", f"anchor: {LINK}", "legacy: `OLD-1`",
                  "note: kick-off"]),
        "",
        "### TASK-2 Child step",
        "",
        DOT.join(["status: READY", "date: 2026-09-01", f"anchor: {LINK}",
                  "superseded by: TASK-3 Replacement step"]),
        "",
        "### TASK-3 Replacement step",
        "",
        DOT.join(["status: READY", "date: 2026-09-01", f"anchor: {LINK}",
                  "supersedes: TASK-2 Child step", "note: replaces TASK-2 Child step"]),
        "",
        "children of other types: ISSUE-1 Found bug",
        ""])
    assert text(out / "ISSUE.md") == "\n".join([
        header(root),
        "# ISSUE entities",
        "",
        "1 entity. Back to the [overview](README.md).",
        "",
        "| status | entities |",
        "| --- | --- |",
        "| OPEN | 1 |",
        "| INVESTIGATING | 0 |",
        "| RESOLVED | 0 |",
        "| WONT_FIX | 0 |",
        "",
        "## ISSUE-1 Found bug",
        "",
        DOT.join(["status: OPEN", "date: 2026-09-01", f"anchor: {LINK}",
                  "parent: TASK-3 Replacement step"]),
        ""])
    assert text(out / "MODEL.md") == "\n".join([
        header(root),
        "# MODEL entities",
        "",
        "No MODEL entity is registered. Back to the [overview](README.md).",
        "",
        "| status | entities |",
        "| --- | --- |",
        "| DRAFT | 0 |",
        "| IN_FORCE | 0 |",
        "| SUPERSEDED | 0 |",
        ""])


def test_output_is_deterministic_lf_utf8_and_location_independent(tmp_path, capsys):
    rows = [row("TASK-1", "中文 root", legacy="OLD-1"), row("TASK-2", "Child", parent="TASK-1"),
            row("ISSUE-1", "Bug", parent="TASK-2", note="see TASK-1")]
    root = make_project(tmp_path / "p", rows, git=True)
    out = generate(capsys, root)
    first = snapshot(out)

    code, report = index(capsys, root, "--out", str(out))
    assert code == 0
    assert report["written"] == [] and report["unchanged"] == ["README.md", "TASK.md", "ISSUE.md", "MODEL.md"]
    assert snapshot(out) == first
    for data in first.values():
        assert b"\r" not in data
        assert data.endswith(b"\n") and not data.endswith(b"\n\n")
        data.decode("utf-8")

    # An exported copy elsewhere (no Git repository) renders byte-identical pages.
    copy = tmp_path / "elsewhere" / "exported"
    shutil.copytree(root, copy, ignore=shutil.ignore_patterns(".git", "index"))
    assert not (copy / ".git").exists()
    assert snapshot(generate(capsys, copy)) == first


def test_config_out_dir_is_used_and_out_flag_overrides_it(tmp_path, capsys, monkeypatch):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")], index='out_dir = "catalogue"\n')

    monkeypatch.chdir(root / "docs")
    capsys.readouterr()
    assert main(["index", "--json"]) == 0
    report = json.loads(capsys.readouterr().out)
    assert report["out_dir"] == "catalogue"
    assert (root / "catalogue" / "README.md").is_file()
    assert DOT + "anchor: [`docs/proposal.md`](../docs/proposal.md)" in fields_of(
        text(root / "catalogue" / "TASK.md"), "TASK-1")

    before = snapshot(root / "catalogue")
    code, report = index(capsys, root, "--out", str(root / "elsewhere"))
    assert code == 0 and (root / "elsewhere" / "TASK.md").is_file()
    assert report["out_dir"] == "elsewhere"
    assert snapshot(root / "catalogue") == before

    # A relative --out resolves against the current directory, like --root.
    capsys.readouterr()
    assert main(["index", "--root", str(root), "--out", "relative-out", "--json"]) == 0
    assert (root / "docs" / "relative-out" / "MODEL.md").is_file()
    assert not (root / "relative-out").exists()


def test_out_outside_the_project_is_refused(tmp_path, capsys, monkeypatch):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")], git=True)
    outside = tmp_path / "outside"
    (outside / "target").mkdir(parents=True)
    (root / "docs" / "linkout").symlink_to(outside / "target")
    (root / "docs" / "gitlink").symlink_to(root / ".git")
    (root / "docs" / "ledgerlink").symlink_to(root / ".ledger")

    monkeypatch.chdir(root)
    attempts = [
        "..",                                   # the parent of the project root
        str(outside / "absolute"),              # an absolute path elsewhere
        str(root / ".." / "outside" / "dots"),  # ".." inside an absolute path
        "docs/linkout",                         # a link inside the project to the outside
        "docs/gitlink",                         # a link to .git
        "docs/ledgerlink",                      # a link to the registry directory
    ]
    for out in attempts:
        capsys.readouterr()
        code = main(["index", "--root", str(root), "--out", out, "--json"])
        report = json.loads(capsys.readouterr().out)
        assert code == 2, out
        assert report["issues"][0]["code"] == "ERR_INDEX_OUT_DIR", out

    # Nothing was written outside the project, into .git or next to the registry.
    assert sorted(path.name for path in tmp_path.iterdir()) == ["outside", "p"]
    assert sorted(path.name for path in outside.iterdir()) == ["target"]
    assert list((outside / "target").iterdir()) == []
    assert sorted(path.name for path in (root / ".ledger").iterdir()) == ["ENTITY_REGISTRY.md"]
    assert not (root / ".git" / "README.md").exists()


def test_symlinked_config_out_dir_is_an_out_dir_error(tmp_path, capsys):
    for out_dir, link, target in [("docs/index", "docs/index", "catalogue"),
                                  ("pages/index", "pages", "real-pages")]:
        root = make_project(tmp_path / out_dir.replace("/", "-"), [row("TASK-1", "Only")],
                            index=f'out_dir = "{out_dir}"\n')
        (root / target).mkdir()
        (root / link).symlink_to(root / target)

        for extra in ((), ("--check",)):
            code, report = index(capsys, root, *extra)
            assert code == 2, (out_dir, extra)
            issue = report["issues"][0]
            assert issue["code"] == "ERR_INDEX_OUT_DIR"
            assert out_dir in issue["reason"] and "out_dir" in issue["suggestion"]
        assert list((root / target).iterdir()) == []


def test_registry_directory_is_refused_whatever_the_registry_suffix(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")])
    (root / ".ledger" / "ENTITY_REGISTRY.md").rename(root / ".ledger" / "REGISTRY.txt")
    config = root / "ledger.toml"
    config.write_text(text(config).replace(".ledger/ENTITY_REGISTRY.md", ".ledger/REGISTRY.txt"),
                      encoding="utf-8")

    code, report = index(capsys, root, "--out", str(root / ".ledger"))
    assert code == 2
    assert report["issues"][0]["code"] == "ERR_INDEX_OUT_DIR"
    assert sorted(path.name for path in (root / ".ledger").iterdir()) == ["REGISTRY.txt"]

    config.write_text(text(config) + '\n[index]\nout_dir = ".ledger"\n', encoding="utf-8")
    code, report = index(capsys, root)
    assert code == 2
    assert report["issues"][0]["code"] == "ERR_INDEX_OUT_DIR"
    assert sorted(path.name for path in (root / ".ledger").iterdir()) == ["REGISTRY.txt"]


def test_index_without_an_output_directory_is_a_configuration_error(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")])
    code, report = index(capsys, root)

    assert code == 2
    issue = report["issues"][0]
    assert issue["code"] == "ERR_INDEX_OUT_DIR"
    assert "--out" in issue["reason"] and "[index]" in issue["reason"]
    assert list(root.rglob("README.md")) == []


def test_check_passes_on_a_fresh_index_and_writes_nothing(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    out = root / "docs" / "index"
    before = snapshot(out)

    code, report = index(capsys, root, "--check")
    assert code == 0
    assert report["status"] == "PASS"
    assert report["pages"] == ["README.md", "TASK.md", "ISSUE.md", "MODEL.md"]
    assert (report["missing"], report["stale"], report["extra"]) == ([], [], [])
    assert report["registry_sha256"] == hashlib.sha256(
        (root / ".ledger" / "ENTITY_REGISTRY.md").read_bytes()).hexdigest()
    assert snapshot(out) == before


def test_check_reports_every_page_stale_after_a_registry_change(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    registry = root / ".ledger" / "ENTITY_REGISTRY.md"
    registry.write_text(text(registry).replace("| Alpha |", "| Alpha renamed |"), encoding="utf-8")
    before = snapshot(root / "docs" / "index")

    code, report = index(capsys, root, "--check")
    assert code == 1 and report["status"] == "FAIL"
    # Every page header carries the registry fingerprint, so every page is stale.
    assert report["stale"] == ["README.md", "TASK.md", "ISSUE.md", "MODEL.md"]
    assert report["missing"] == [] and report["extra"] == []
    assert snapshot(root / "docs" / "index") == before


def test_check_reports_a_hand_edited_page(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    page = root / "docs" / "index" / "TASK.md"
    page.write_text(text(page) + "hand edit\n", encoding="utf-8")

    code, report = index(capsys, root, "--check")
    assert code == 1
    assert (report["missing"], report["stale"], report["extra"]) == ([], ["TASK.md"], [])


def test_check_reports_missing_pages_and_does_not_create_the_directory(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    out = root / "docs" / "index"
    (out / "ISSUE.md").unlink()

    code, report = index(capsys, root, "--check")
    assert code == 1
    assert (report["missing"], report["stale"], report["extra"]) == (["ISSUE.md"], [], [])

    shutil.rmtree(out)
    code, report = index(capsys, root, "--check")
    assert code == 1
    assert report["missing"] == ["README.md", "TASK.md", "ISSUE.md", "MODEL.md"]
    assert not out.exists()


def test_check_reports_extra_markdown_pages_but_ignores_other_files(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    out = root / "docs" / "index"
    (out / "notes.md").write_text("hand-written\n", encoding="utf-8")
    (out / ".gitkeep").write_text("", encoding="utf-8")
    (out / "nested").mkdir()
    (out / "nested" / "deep.md").write_text("not a top-level page\n", encoding="utf-8")

    code, report = index(capsys, root, "--check")
    assert code == 1
    assert (report["missing"], report["stale"], report["extra"]) == ([], [], ["notes.md"])


def test_check_text_output_lists_the_differences(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    assert index(capsys, root)[0] == 0
    (root / "docs" / "index" / "ISSUE.md").unlink()
    (root / "docs" / "index" / "notes.md").write_text("x\n", encoding="utf-8")

    capsys.readouterr()
    assert main(["index", "--root", str(root), "--check"]) == 1
    output = capsys.readouterr().out
    assert "FAIL" in output
    assert any(line.split() == ["missing", "ISSUE.md"] for line in output.splitlines())
    assert any(line.split() == ["extra", "notes.md"] for line in output.splitlines())


def test_writer_reports_but_never_deletes_unknown_pages(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha")], index='out_dir = "docs/index"\n')
    out = root / "docs" / "index"
    out.mkdir(parents=True)
    (out / "notes.md").write_text("keep me\n", encoding="utf-8")

    code, report = index(capsys, root)
    assert code == 0
    assert report["status"] == "WRITTEN"
    assert report["written"] == ["README.md", "TASK.md", "ISSUE.md", "MODEL.md"]
    assert report["extra"] == ["notes.md"]
    assert text(out / "notes.md") == "keep me\n"


def test_notes_follow_every_registered_id_with_its_full_name(tmp_path, capsys):
    rows = [row("TASK-1", "Alpha plan"),
            row("TASK-2", "Beta", note="blocked by TASK-1; see TASK-1 Alpha plan and ISSUE-1/TASK-99"),
            row("ISSUE-1", "Crash on start")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")

    assert fields_of(page, "TASK-2").endswith(
        "note: blocked by TASK-1 Alpha plan; see TASK-1 Alpha plan and ISSUE-1 Crash on start/TASK-99")


def test_type_description_mentions_are_followed_by_full_names(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha plan")])
    config = root / "ledger.toml"
    config.write_text(text(config).replace('description = "Work items"',
                                           'description = "Work items under TASK-1"'), encoding="utf-8")
    out = generate(capsys, root)

    assert "Description: Work items under TASK-1 Alpha plan" in text(out / "TASK.md").splitlines()
    assert "| TASK | Work items under TASK-1 Alpha plan | 1 | READY 1 | [TASK.md](TASK.md) |" in text(
        out / "README.md").splitlines()


def test_registry_text_cannot_inject_markdown(tmp_path, capsys):
    rows = [row("TASK-1", "Use <details> *now* `x` #"),
            row("TASK-2", "NOT_PRIMARY __init__.py",
                note="see [site](http://example.invalid) &amp; more <b>x</b> ~y~ $5 a\\*b")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")

    assert "## TASK-1 Use \\<details> \\*now\\* \\`x\\` \\#" in page.splitlines()
    assert "## TASK-2 NOT_PRIMARY \\_\\_init\\_\\_.py" in page.splitlines()
    assert fields_of(page, "TASK-2").endswith(
        "note: see [site\\](http://example.invalid) \\&amp; more \\<b>x\\</b> \\~y\\~ \\$5 a\\\\\\*b")


def test_legacy_alias_is_rendered_as_inline_code(tmp_path, capsys):
    rows = [row("TASK-1", "Renamed", legacy="M0@screening; Gate A0"), row("TASK-2", "Tick", legacy="a`b")]
    page = text(generate(capsys, make_project(tmp_path / "p", rows)) / "TASK.md")

    assert DOT + "legacy: `M0@screening; Gate A0`" in fields_of(page, "TASK-1")
    assert DOT + "legacy: ``a`b``" in fields_of(page, "TASK-2")


def test_index_table_is_parsed_with_defaults(tmp_path):
    configured = make_project(tmp_path / "p", [row("TASK-1", "Only")],
                              index='out_dir = "docs/index"\ncheck = true\n')
    plain = make_project(tmp_path / "q", [row("TASK-1", "Only")])

    cfg = LedgerConfig.load(configured / "ledger.toml")
    assert (cfg.index.out_dir, cfg.index.check) == ("docs/index", True)
    cfg = LedgerConfig.load(plain / "ledger.toml")
    assert (cfg.index.out_dir, cfg.index.check) == ("", False)


@pytest.mark.parametrize("table", [
    'out_dir = "docs/index"\nunknown = 1\n',
    "out_dir = 5\n",
    'out_dir = "/abs/index"\n',
    'out_dir = "../index"\n',
    'out_dir = "docs\\\\index"\n',
    'out_dir = "docs/index/"\n',
    'out_dir = ".git/index"\n',
    'out_dir = "docs/index"\ncheck = "yes"\n',
    "check = true\n",
])
def test_invalid_index_table_is_rejected(tmp_path, table):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")], index=table)

    with pytest.raises(LedgerError) as error:
        LedgerConfig.load(root / "ledger.toml")
    assert error.value.issue.code == "ERR_CONFIG"
    # The table itself is accepted; the diagnostic names the offending index field.
    assert error.value.issue.reason.startswith("index")


def test_index_refuses_a_registry_with_broken_relations(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Orphan", parent="TASK-9")])
    code, report = index(capsys, root, "--out", str(root / "docs" / "index"))

    assert code == 1
    assert report["issues"][0]["code"] == "ERR_RELATION_NOT_FOUND"
    assert not (root / "docs" / "index").exists()


def test_index_refuses_to_write_next_to_the_registry(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Only")])
    code, report = index(capsys, root, "--out", str(root / ".ledger"))

    assert code == 2
    assert report["issues"][0]["code"] == "ERR_INDEX_OUT_DIR"
    assert sorted(path.name for path in (root / ".ledger").iterdir()) == ["ENTITY_REGISTRY.md"]


def test_index_leaves_registry_and_config_untouched(tmp_path, capsys):
    root = make_project(tmp_path / "p", [row("TASK-1", "Alpha", legacy="OLD-1")],
                        index='out_dir = "docs/index"\n')
    sources = [root / "ledger.toml", root / ".ledger" / "ENTITY_REGISTRY.md"]
    before = [path.read_bytes() for path in sources]

    assert index(capsys, root)[0] == 0
    assert index(capsys, root, "--check")[0] == 0
    assert [path.read_bytes() for path in sources] == before
