"""Public CLI; unsupported views never fall back to the worktree."""
import argparse
import json
from pathlib import Path
import sys
from .config import LedgerConfig, find_config_file
from .errors import LedgerError
from .git import repository_root, safe_file
from .index import build_index, compare_index, display_path, resolve_out_dir, write_index
from .linter import aggregate, check_registry_invariants, scan, scan_legacy
from .registry import EntityRegistry
from .search import search_entities

DEFAULT_CONFIG_TEMPLATE = '''[ledger]
schema_version = "1.0"
registry_path = ".ledger/ENTITY_REGISTRY.md"
allow_gaps = true
# order defaults to the ID serial; set true to treat order as a render-only plan position.
independent_order = false
code_extensions = [".py", ".ts", ".js", ".go", ".rs", ".json", ".md"]
ignore_globs = []

# Exempt only declared non-registered tokens (for example teaching counterexamples).
# [reference_exemptions]
# "docs/example.md" = ["TASK-014"]

# Per-type catalogue pages written by repo-ledger index; check = true lets check verify them.
# [index]
# out_dir = ".ledger/index"
# check = true

[legacy_guard]
enabled = true
scope_globs = ["*.py", "**/*.py", "*.ts", "**/*.ts", "*.js", "**/*.js", "*.go", "**/*.go", "*.rs", "**/*.rs", "*.json", "**/*.json", "*.md", "**/*.md"]
exclude_globs = []
forbidden_tokens = []
file_exemptions = []
column_masks = {}
fence_exemptions = []
string_line_exemptions = {}
'''

def output(value):
    print(json.dumps(value, ensure_ascii=False, indent=2))


def run_index(args, root, cfg):
    """Write the per-type pages, or with --check compare them and write nothing."""
    out_dir = resolve_out_dir(root, cfg, args.out)
    build = build_index(root, cfg, out_dir)
    shown = display_path(root, out_dir)
    result = {"status": "WRITTEN", "out_dir": shown, "registry": build.registry_path,
              "registry_sha256": build.registry_sha256, "pages": list(build.pages)}
    fingerprint = build.registry_sha256[:12]
    if args.check:
        differences = compare_index(build, out_dir)
        failed = any(differences.values())
        result.update(status="FAIL" if failed else "PASS", **differences)
        if args.json:
            output(result)
        elif failed:
            print(f"FAIL: index pages in {shown} differ from the registry (registry-sha256 {fingerprint})")
            for kind, names in differences.items():
                for name in names:
                    print(f"{kind:<8}{name}")
        else:
            print(f"PASS: {len(build.pages)} index pages in {shown} match the registry "
                  f"(registry-sha256 {fingerprint})")
        return int(failed)
    result.update(write_index(build, out_dir))
    if args.json:
        output(result)
    else:
        print(f"Wrote {len(result['written'])} of {len(build.pages)} index pages to {shown} "
              f"({len(result['unchanged'])} unchanged; registry-sha256 {fingerprint})")
        for name in result["extra"]:
            print(f"extra   {name} (not generated by repo-ledger index; left in place)")
    return 0

def main(argv=None):
    parser = argparse.ArgumentParser(prog="repo-ledger")
    commands = parser.add_subparsers(dest="command", required=True)
    for command in ("init", "allocate", "lookup", "search", "update", "check", "check-legacy", "tree", "index"):
        p = commands.add_parser(command)
        p.add_argument("--root", type=Path)
        p.add_argument("--json", action="store_true")
        if command == "allocate":
            p.add_argument("type")
            p.add_argument("name")
            for flag in ("anchor", "status", "parent", "supersedes", "note", "legacy", "order"):
                p.add_argument("--" + flag, default=None if flag == "status" else "")
        if command == "lookup":
            p.add_argument("entity_id")
        if command == "search":
            p.add_argument("query")
            p.add_argument("--limit", type=int, default=5)
        if command == "update":
            p.add_argument("entity_id")
            p.add_argument("--status")
            p.add_argument("--note")
            p.add_argument("--order")
            p.add_argument("--expected-status")
        if command == "check":
            p.add_argument("--staged", action="store_true")
            p.add_argument("--commit")
            p.add_argument("--incremental", action="store_true")
        if command == "index":
            p.add_argument("--out", type=Path,
                           help="output directory, relative to the current directory; overrides [index] out_dir")
            p.add_argument("--check", action="store_true",
                           help="compare the pages on disk with a regeneration; write nothing")
    args = parser.parse_args(argv)
    try:
        if args.command == "check" and (args.staged or args.commit or args.incremental):
            raise LedgerError("ERR_UNSUPPORTED_VIEW", "Index, commit-tree and incremental checks are not implemented",
                              category="configuration")
        cfg_path = find_config_file(args.root)
        if args.command == "init":
            root = (args.root or Path.cwd()).resolve()
            repository_root(root)
            cfg_path = root / "ledger.toml"
            if cfg_path.exists() or (root / ".ledger/ENTITY_REGISTRY.md").exists():
                raise LedgerError("ERR_ALREADY_INITIALIZED", "Refusing to overwrite existing configuration or registry")
            # Exclusive creation protects existing user configuration.
            with cfg_path.open("x", encoding="utf-8") as stream:
                stream.write(DEFAULT_CONFIG_TEMPLATE)
            cfg = LedgerConfig.load(cfg_path)
            path = safe_file(root, cfg.registry_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("x", encoding="utf-8") as stream:
                stream.write("<!-- schema: 1.0 -->\n# Entity Registry\n\n"
                             "| id | name | status | parent | order | anchor | supersedes | date | legacy | note |\n"
                             "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
            output({"status": "INITIALIZED", "root": str(root)})
            return 0
        if cfg_path is None:
            raise LedgerError("ERR_CONFIG", "No ledger.toml; run init at the repository root", category="configuration")
        if args.command == "index":
            # Pages depend only on ledger.toml and the registry bytes, so no Git is needed.
            return run_index(args, cfg_path.parent.resolve(), LedgerConfig.load(cfg_path))
        root = repository_root(cfg_path.parent)
        cfg = LedgerConfig.load(cfg_path)
        registry = EntityRegistry.load(safe_file(root, cfg.registry_path), cfg)
        if args.command == "allocate":
            row = registry.allocate(args.type, args.name, args.status, args.parent, args.anchor,
                                    args.supersedes, args.note, args.legacy, args.order or None)
            output(row.to_dict())
        elif args.command == "search":
            result = search_entities(registry, args.query, args.limit)
            if args.json:
                output(result)
            else:
                print(f"{result['total']} matches; showing {len(result['results'])}")
                for row in result["results"]:
                    print(f"{row['id']} [{row['status']}] {row['name']} anchor={row['anchor'] or '-'}")
        elif args.command == "update":
            row = registry.update(args.entity_id, status=args.status, note=args.note,
                                  order=args.order, expected_status=args.expected_status)
            if args.json:
                output(row.to_dict())
            else:
                print(f"Updated {row.id} [{row.status}] {row.name}")
        elif args.command == "lookup":
            row = registry.lookup(args.entity_id)
            if row is None:
                raise LedgerError("ERR_UNREGISTERED_ENTITY", "Entity not found", entity=args.entity_id)
            if args.json:
                output(row.to_dict())
            else:
                print(f"ID:         {row.id}\nName:       {row.name}\nStatus:     {row.status}\n"
                      f"Anchor:     {row.anchor}\nLegacy:     {row.legacy}")
        elif args.command == "tree":
            # Retained prototype convenience; validation prevents cycles.
            issues = check_registry_invariants(registry, root)
            if issues:
                issue = issues[0]
                raise LedgerError(issue.code, issue.reason, issue.location, issue.entity)
            # order is a render-only plan position; ledger rows stay in append-only serial order.
            grouped = {}
            for row in registry.rows:
                grouped.setdefault(row.parent, []).append(row)

            def order_key(candidate):
                return (int(candidate.order) if candidate.order.isdigit() else 0, candidate.id)

            def render(node, depth):
                print(f"{'  ' * depth}{node.id} [{node.status}] {node.name} order={node.order}")
                for child in sorted(grouped.get(node.id, []), key=order_key):
                    render(child, depth + 1)

            for top in sorted(grouped.get("", []), key=order_key):
                render(top, 0)
        elif args.command == "check-legacy":
            legacy_issues, legacy_audit = scan_legacy(root, registry)
            scope = {"view": "worktree", "legacy_guard": legacy_audit}
            result = {"status": "FAIL" if legacy_issues else "PASS", "entities_count": len(registry.rows),
                      "complete": not any(i.category == "incomplete" for i in legacy_issues),
                      "scope": scope, "issues": aggregate(legacy_issues)}
            if args.json:
                output(result)
            else:
                print(f"{result['status']}: legacy guard, {len(legacy_audit['scanned'])} files scanned")
                for issue in result["issues"]:
                    print(f"[{issue['code']}] {issue['location']} {issue['entity']}: {issue['reason']} "
                          f"(count={issue['count']}); {issue['suggestion']}")
            return 3 if not result["complete"] else int(bool(legacy_issues))
        else:
            issues = check_registry_invariants(registry, root)
            scanned, audit = scan(root, registry)
            issues += scanned
            legacy_issues, legacy_audit = scan_legacy(root, registry)
            issues += legacy_issues
            audit["legacy_guard"] = legacy_audit
            result = {"status": "FAIL" if issues else "PASS", "entities_count": len(registry.rows),
                      "complete": not any(i.category == "incomplete" for i in issues),
                      "scope": audit, "issues": aggregate(issues)}
            if args.json:
                output(result)
            else:
                print(f"{result['status']}: worktree, {len(audit['scanned'])} files scanned")
                for issue in result["issues"]:
                    print(f"[{issue['code']}] {issue['location']} {issue['entity']}: {issue['reason']} "
                          f"(count={issue['count']}); {issue['suggestion']}")
            return 3 if not result["complete"] else int(bool(issues))
        return 0
    except (LedgerError, OSError, UnicodeError) as exc:
        if not isinstance(exc, LedgerError):
            exc = LedgerError("ERR_READ_WRITE", str(exc), category="incomplete")
        issue = exc.issue
        if issue.code == "ERR_UPDATE_CONFLICT":
            issue.suggestion = "Run lookup again, review the current evidence, and retry only if the update is still valid."
        elif issue.code == "ERR_NO_UPDATE":
            issue.suggestion = "Specify --status and/or --note; use an empty --note to clear the note."
        elif issue.code == "ERR_SEARCH_QUERY":
            issue.suggestion = "Supply a nonblank literal keyword, ID, or documented legacy alias."
        elif issue.code == "ERR_SEARCH_LIMIT":
            issue.suggestion = "Choose --limit from 1 through 100; the default is 5."
        elif issue.code == "ERR_LEGACY_READONLY":
            issue.suggestion = "Resolve the alias with lookup, then update the returned current ID; never reassign the alias."
        elif issue.code == "ERR_REGISTRY_PATH_CHANGED":
            issue.suggestion = "Reload ledger.toml and lookup the entity in the configured registry before retrying."
        elif issue.code == "ERR_ORDER_FIXED":
            issue.suggestion = ("Leave order equal to the ID serial, or set "
                                "independent_order = true in ledger.toml to replan it.")
        elif issue.code == "ERR_DUPLICATE_ORDER":
            issue.suggestion = ("Reuse no order within the same type and parent scope; "
                                "choose a free value or let allocate pick the next one.")
        elif issue.code == "ERR_INVALID_ORDER":
            issue.suggestion = "Use a positive integer without leading zeros."
        elif issue.code == "ERR_INDEX_OUT_DIR":
            issue.suggestion = ("Pass --out DIR or set [index] out_dir to a dedicated directory; "
                                "the index never overwrites or deletes files it did not generate.")
        if args.json:
            output({"status": "FAIL", "complete": False, "issues": [issue.to_dict()]})
        else:
            print(f"[{issue.code}] {issue.location} {issue.entity}: {issue.reason}; {issue.suggestion}", file=sys.stderr)
        return {"violation": 1, "configuration": 2, "incomplete": 3}[issue.category]

if __name__ == "__main__":
    sys.exit(main())
