"""Deterministic per-type Markdown catalogue pages rendered from the registry.

The pages are a pure function of ledger.toml and the registry bytes: no Git, no clock,
no filesystem state beyond those two files. Freshness is a byte-for-byte comparison with
a regeneration, never a date.
"""
from dataclasses import dataclass
import hashlib
import os
from pathlib import Path
import re

from .config import relative_path
from .errors import Issue, LedgerError
from .git import safe_file
from .linter import relation_issues
from .registry import EntityRegistry, atomic_write

OVERVIEW = "README.md"
DOT = " \u00b7 "  # middle dot between the fields of one entity
GENERATED_MARK = "generated by repo-ledger index; do not edit by hand -->"
# Headings stop at level 6; deeper entities continue as nested bullets under it.
LIST_DEPTH = 5
_COMMIT_RE = re.compile(r"[0-9a-fA-F]{7,64}")
_ENTITY_REFERENCE_RE = re.compile(r"&(?:#[0-9]{1,7}|#[xX][0-9a-fA-F]{1,6}|[A-Za-z][A-Za-z0-9]{1,31});")
_ASCII_PUNCTUATION = frozenset("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~")
_UNSAFE_IN_LINK = frozenset(" \"%#'()<>?[\\]^`{|}")
_REGENERATE = "Run repo-ledger index to regenerate the pages, then review and commit them."
_DIFFERENCES = {
    "missing": ("Index page is missing", _REGENERATE),
    "stale": ("Index page differs from the page regenerated from the registry", _REGENERATE),
    "extra": ("Page in the index directory is not generated by repo-ledger index",
              "Delete or move the page; the index directory holds only generated pages."),
}


def markdown_text(value, *, table=False):
    """Escape registry text so it renders as written.

    Ordinary prose, CJK text, intraword underscores and lone comparison signs stay
    byte-identical; only characters that would start Markdown or HTML syntax are
    backslash-escaped. Pipes are escaped inside table cells only.
    """
    out = []
    last = len(value) - 1
    for position, char in enumerate(value):
        before = value[position - 1] if position else ""
        after = value[position + 1] if position < last else ""
        if char == "\\":
            escape = not after or after in _ASCII_PUNCTUATION
        elif char in "`*~$":
            escape = True
        elif char == "_":
            escape = not (before.isalnum() and after.isalnum())
        elif char == "<":
            escape = bool(after) and after.isascii() and (after.isalpha() or after in "/!?")
        elif char == "&":
            escape = _ENTITY_REFERENCE_RE.match(value, position) is not None
        elif char == "]":
            escape = after == "("
        elif char == "|":
            escape = table
        else:
            escape = False
        out.append("\\" + char if escape else char)
    return "".join(out)


def code_span(value):
    """Inline code that survives backticks inside the value."""
    fence = "`" * (max((len(run) for run in re.findall("`+", value)), default=0) + 1)
    pad = " " if value.startswith("`") or value.endswith("`") else ""
    return f"{fence}{pad}{value}{pad}{fence}"


def _heading(level, text):
    body = markdown_text(text)
    trimmed = body.rstrip("#")
    # A trailing run of # would be read as the closing sequence of the heading.
    return "#" * level + " " + trimmed + "\\#" * (len(body) - len(trimmed))


def _link_target(path):
    return "".join(f"%{ord(char):02X}" if char in _UNSAFE_IN_LINK else char for char in path)


def _type(entity_id):
    return entity_id.rsplit("-", 1)[0]


def _serial(entity_id):
    return int(entity_id.rsplit("-", 1)[1])


def _targets(supersedes):
    return [target.strip() for target in supersedes.split(",")] if supersedes else []


def _count(number, singular, plural):
    return f"{number} {singular if number == 1 else plural}"


def page_names(config):
    return [OVERVIEW] + [f"{name}.md" for name in config.types]


def generated_pages(config):
    """Repository-relative paths of the pages the configured [index] generates."""
    return frozenset(f"{config.index.out_dir}/{name}" for name in page_names(config))


def display_path(root, path):
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


@dataclass
class IndexBuild:
    registry_path: str
    registry_sha256: str
    pages: dict


def resolve_out_dir(root, config, cli_out=None):
    """--out (relative to the current directory) wins over [index] out_dir (relative to root)."""
    root = Path(root).resolve()
    location = f"{root / 'ledger.toml'}:1:1"

    def refuse(reason):
        raise LedgerError("ERR_INDEX_OUT_DIR", reason, location, category="configuration")

    if cli_out is not None:
        out_dir = Path(cli_out).resolve()
    elif config.index.out_dir:
        out_dir = safe_file(root, config.index.out_dir).resolve()
    else:
        refuse("No output directory: pass --out DIR or set out_dir in the [index] table of ledger.toml")
    if out_dir == root:
        refuse("The index needs its own directory; the output directory must not be the project root")
    if ".git" in out_dir.parts:
        refuse(f"The output directory must not be inside a .git directory: {out_dir}")
    if out_dir.exists() and not out_dir.is_dir():
        refuse(f"The output path is not a directory: {out_dir}")
    registry = (root / config.registry_path).resolve()
    if registry.parent == out_dir and registry.suffix.lower() == ".md":
        refuse("The output directory holds the registry; choose a dedicated directory for the index")
    return out_dir


def build_index(root, config, out_dir):
    """Render every page in memory from one read of the registry bytes."""
    root = Path(root).resolve()
    if OVERVIEW[:-3] in config.types:
        raise LedgerError("ERR_CONFIG", "Type README would collide with the overview page README.md",
                          f"{root / 'ledger.toml'}:1:1", category="configuration")
    for name, spec in config.types.items():
        if not isinstance(spec.description, str):
            raise LedgerError("ERR_CONFIG", f"types.{name}.description must be a string to render the index",
                              f"{root / 'ledger.toml'}:1:1", category="configuration")
    path = safe_file(root, config.registry_path)
    try:
        data = path.read_bytes()
        text = data.decode("utf-8")
    except (OSError, UnicodeError) as exc:
        raise LedgerError("ERR_READ", str(exc), f"{path}:1:1", category="incomplete") from exc
    registry = EntityRegistry.load(path, config, text=text)
    problems = relation_issues(registry)
    if problems:
        first = problems[0]
        raise LedgerError(first.code, first.reason, first.location, first.entity)
    digest = hashlib.sha256(data).hexdigest()
    renderer = _Renderer(root, config, registry, Path(out_dir), digest)
    return IndexBuild(config.registry_path, digest, renderer.pages())


class _Renderer:
    def __init__(self, root, config, registry, out_dir, digest):
        self.root, self.config, self.registry, self.out_dir = root, config, registry, out_dir
        self.digest = digest
        self.rows = {row.id: row for row in registry.rows}
        self.type_order = {name: position for position, name in enumerate(config.types)}
        # The evidence column keeps the registry's own name: "anchor" or the project "owner".
        self.anchor_label = registry.table_header[registry.fields.index("anchor")]
        prefixes = "|".join(re.escape(name) for name in sorted(config.types, key=len, reverse=True))
        self.mention = re.compile(rf"(?<![A-Za-z0-9_-])(?:{prefixes})-[0-9]+(?![A-Za-z0-9_-])")
        self.same_type_children, self.other_type_children, self.superseded_by = {}, {}, {}
        for row in registry.rows:
            if row.parent:
                same = _type(row.parent) == _type(row.id)
                bucket = self.same_type_children if same else self.other_type_children
                bucket.setdefault(row.parent, []).append(row)
            for target in _targets(row.supersedes):
                self.superseded_by.setdefault(target, []).append(row)
        shown = config.registry_path.replace("-->", "--&gt;")
        self.header = f"<!-- registry: {shown}; registry-sha256: {digest[:12]}; {GENERATED_MARK}"

    # Ordering: siblings by plan order, then numeric ID. Without independent_order the order
    # column equals the ID serial (enforced on load), so this is plain numeric ID order.
    @staticmethod
    def sibling_key(row):
        return int(row.order), _serial(row.id)

    def typed_sibling_key(self, row):
        return (self.type_order[_type(row.id)], *self.sibling_key(row))

    def typed_id_key(self, row):
        return self.type_order[_type(row.id)], _serial(row.id)

    def label(self, entity_id):
        return markdown_text(f"{entity_id} {self.rows[entity_id].name}")

    def annotate(self, value):
        """Follow every registered ID in free text with its full name unless it already is."""
        pieces, position = [], 0
        for match in self.mention.finditer(value):
            row = self.rows.get(match.group(0))
            if row is None or value.startswith(" " + row.name, match.end()):
                continue
            pieces += [value[position:match.end()], " " + row.name]
            position = match.end()
        pieces.append(value[position:])
        return "".join(pieces)

    def prose(self, value, *, table=False):
        return markdown_text(self.annotate(value), table=table)

    def description(self, type_name):
        return " ".join(self.config.types[type_name].description.split())

    def owner(self, value):
        if _COMMIT_RE.fullmatch(value) or not relative_path(value):
            return code_span(value)
        try:
            target = os.path.relpath(self.root / value, self.out_dir)
        except ValueError as exc:
            raise LedgerError("ERR_INDEX_OUT_DIR", f"Cannot link {value} from {self.out_dir}: {exc}",
                              category="configuration") from exc
        return f"[{code_span(value)}]({_link_target(Path(target).as_posix())})"

    def fields(self, row, *, other_type_parent=False, other_type_children=()):
        parts = [f"status: {markdown_text(row.status)}", f"date: {markdown_text(row.date)}"]
        if row.anchor:
            parts.append(f"{self.anchor_label}: {self.owner(row.anchor)}")
        if other_type_parent:
            parts.append(f"parent: {self.label(row.parent)}")
        if row.legacy:
            parts.append(f"legacy: {code_span(row.legacy)}")
        if row.supersedes:
            parts.append("supersedes: " + "; ".join(self.label(target) for target in _targets(row.supersedes)))
        later = sorted(self.superseded_by.get(row.id, []), key=self.typed_id_key)
        if later:
            parts.append("superseded by: " + "; ".join(self.label(other.id) for other in later))
        if other_type_children:
            parts.append(self.children_line(other_type_children))
        if row.note:
            parts.append(f"note: {self.prose(row.note)}")
        return DOT.join(parts)

    def children_line(self, children):
        return "children of other types: " + "; ".join(self.label(child.id) for child in children)

    def entity_block(self, row, depth):
        children = sorted(self.other_type_children.get(row.id, []), key=self.typed_sibling_key)
        if depth >= LIST_DEPTH:
            indent = "  " * (depth - LIST_DEPTH)
            return f"{indent}- {self.label(row.id)}{DOT}{self.fields(row, other_type_children=children)}"
        lines = [_heading(depth + 2, f"{row.id} {row.name}"), "",
                 self.fields(row, other_type_parent=depth == 0 and bool(row.parent))]
        if children:
            lines += ["", self.children_line(children)]
        return "\n".join(lines)

    def tree(self, type_name, rows):
        top = [row for row in rows if not row.parent or _type(row.parent) != type_name]
        stack = [(row, 0) for row in reversed(sorted(top, key=self.sibling_key))]
        blocks, bullets, rendered = [], [], 0
        while stack:
            row, depth = stack.pop()
            rendered += 1
            if depth >= LIST_DEPTH:
                bullets.append(self.entity_block(row, depth))
            else:
                if bullets:
                    blocks.append("\n".join(bullets))
                    bullets = []
                blocks.append(self.entity_block(row, depth))
            children = sorted(self.same_type_children.get(row.id, []), key=self.sibling_key)
            stack.extend((child, depth + 1) for child in reversed(children))
        if bullets:
            blocks.append("\n".join(bullets))
        if rendered != len(rows):
            # Relation validation rules this out; never drop an entity silently.
            raise LedgerError("ERR_RELATION_CYCLE",
                              f"{len(rows) - rendered} {type_name} entities are unreachable from a top-level entity",
                              f"{self.registry.path}:1:1")
        return blocks

    def status_counts(self, type_name, rows):
        counts = {status: 0 for status in self.config.types[type_name].allowed_statuses}
        for row in rows:
            counts[row.status] += 1
        return counts

    def type_page(self, type_name):
        rows = [row for row in self.registry.rows if _type(row.id) == type_name]
        blocks = [f"{self.header}\n# {markdown_text(type_name)} entities"]
        if self.description(type_name):
            blocks.append(f"Description: {self.prose(self.description(type_name))}")
        back = "Back to the [overview](README.md)."
        if rows:
            blocks.append(f"{_count(len(rows), 'entity', 'entities')}. {back}")
        else:
            blocks.append(f"No {markdown_text(type_name)} entity is registered. {back}")
        table = ["| status | entities |", "| --- | --- |"]
        table += [f"| {markdown_text(status, table=True)} | {count} |"
                  for status, count in self.status_counts(type_name, rows).items()]
        blocks.append("\n".join(table))
        blocks += self.tree(type_name, rows)
        return "\n\n".join(blocks) + "\n"

    def overview(self):
        total = len(self.registry.rows)
        summary = (f"Registry {code_span(self.config.registry_path)} (sha256 {code_span(self.digest[:12])}): "
                   f"{_count(total, 'entity', 'entities')} in {_count(len(self.config.types), 'type', 'types')}.")
        table = ["| type | description | entities | by status | page |", "| --- | --- | --- | --- | --- |"]
        for type_name in self.config.types:
            rows = [row for row in self.registry.rows if _type(row.id) == type_name]
            by_status = ", ".join(f"{markdown_text(status, table=True)} {count}"
                                  for status, count in self.status_counts(type_name, rows).items() if count)
            page = f"{type_name}.md"
            table.append(" | ".join([
                f"| {markdown_text(type_name, table=True)}",
                self.prose(self.description(type_name), table=True),
                str(len(rows)), by_status or "none",
                f"[{markdown_text(page, table=True)}]({_link_target(page)}) |"]))
        return "\n\n".join([f"{self.header}\n# Entity index", summary, "\n".join(table)]) + "\n"

    def pages(self):
        pages = {OVERVIEW: self.overview()}
        for type_name in self.config.types:
            pages[f"{type_name}.md"] = self.type_page(type_name)
        return pages


def _is_generated(data):
    first = data.split(b"\n", 1)[0].decode("utf-8", "replace").rstrip("\r")
    return first.startswith("<!-- registry: ") and first.endswith(GENERATED_MARK)


def unknown_pages(build, out_dir):
    """Top-level Markdown files in the output directory that the generator would not write."""
    if not out_dir.is_dir():
        return []
    return sorted(entry.name for entry in out_dir.iterdir()
                  if entry.name not in build.pages and entry.suffix.lower() == ".md"
                  and (entry.is_file() or entry.is_symlink()))


def compare_index(build, out_dir):
    """Read-only freshness check: missing, stale and extra pages; nothing is written."""
    missing, stale = [], []
    for name, text in build.pages.items():
        path = out_dir / name
        if path.is_symlink() or not path.is_file():
            missing.append(name)
        elif path.read_bytes() != text.encode("utf-8"):
            stale.append(name)
    return {"missing": missing, "stale": stale, "extra": unknown_pages(build, out_dir)}


def write_index(build, out_dir):
    """Write changed pages; never overwrite a file it did not generate, never delete anything."""
    pending, unchanged = [], []
    for name, text in build.pages.items():
        path = out_dir / name
        data = text.encode("utf-8")
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise LedgerError("ERR_INDEX_OUT_DIR", f"Refusing to replace {path}: not a regular file",
                              f"{path}:1:1", category="configuration")
        if path.exists():
            current = path.read_bytes()
            if current == data:
                unchanged.append(name)
                continue
            if not _is_generated(current):
                raise LedgerError("ERR_INDEX_OUT_DIR",
                                  f"Refusing to overwrite {path}: it was not generated by repo-ledger index",
                                  f"{path}:1:1", category="configuration")
        pending.append((name, path, text))
    for _, path, text in pending:
        atomic_write(path, text)
    return {"written": [name for name, _, _ in pending], "unchanged": unchanged,
            "extra": unknown_pages(build, out_dir)}


def verify_configured_index(root, config):
    """Staleness check that repo-ledger check runs when [index] check = true.

    Returns (issues, audit, generated). The generated page paths are excluded from the
    prose scans because this check verifies their content by byte-exact regeneration;
    when the pages cannot be regenerated nothing is excluded and check is incomplete.
    """
    out_rel = config.index.out_dir
    audit = {"out_dir": out_rel, "registry_sha256": None,
             "pages": [f"{out_rel}/{name}" for name in page_names(config)],
             "missing": [], "stale": [], "extra": []}
    try:
        out_dir = resolve_out_dir(root, config)
        build = build_index(root, config, out_dir)
    except LedgerError as exc:
        if exc.issue.category == "configuration":
            raise
        return [Issue("ERR_INDEX_UNVERIFIED", f"{out_rel}:1:1", exc.issue.entity,
                      f"Index pages could not be regenerated: {exc.issue.reason}",
                      "Fix the registry problem reported by check, then run repo-ledger index.",
                      "incomplete")], audit, frozenset()
    audit["registry_sha256"] = build.registry_sha256
    issues = []
    for kind, names in compare_index(build, out_dir).items():
        reason, suggestion = _DIFFERENCES[kind]
        for name in names:
            audit[kind].append(f"{out_rel}/{name}")
            issues.append(Issue("ERR_INDEX_STALE", f"{out_rel}/{name}:1:1", "", reason, suggestion))
    return issues, audit, generated_pages(config)
